# Generated by Django 2.2.2 on 2019-06-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_user_agent',
            field=models.TextField(blank=True),
        ),
    ]
