# Generated by Django 2.2.2 on 2019-06-05 19:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20190604_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/kodziek/PycharmProjects/secret_share/private_media/'), upload_to=''),
        ),
    ]
